/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4.views;

/**
 *
 * @author Mauricio
 */
public class Colegio extends javax.swing.JFrame {

    /**
     * Creates new form Colegio
     */
    public Colegio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barMainMenu = new javax.swing.JMenuBar();
        mnuAlumno = new javax.swing.JMenu();
        mniAgregarAlumno = new javax.swing.JMenuItem();
        mniListarAlumnos = new javax.swing.JMenuItem();
        mnuMateria = new javax.swing.JMenu();
        mniAgregarMateria = new javax.swing.JMenuItem();
        mniListarMaterias = new javax.swing.JMenuItem();
        mnuRegistro = new javax.swing.JMenu();
        mniInscripcionMateria = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuAlumno.setText("Alumno");

        mniAgregarAlumno.setText("Agregar alumno");
        mniAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarAlumnoActionPerformed(evt);
            }
        });
        mnuAlumno.add(mniAgregarAlumno);

        mniListarAlumnos.setText("Lista de alumnos");
        mnuAlumno.add(mniListarAlumnos);

        barMainMenu.add(mnuAlumno);

        mnuMateria.setText("Materia");

        mniAgregarMateria.setText("Agregar Materia");
        mniAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarMateriaActionPerformed(evt);
            }
        });
        mnuMateria.add(mniAgregarMateria);

        mniListarMaterias.setText("Lista de materias");
        mnuMateria.add(mniListarMaterias);

        barMainMenu.add(mnuMateria);

        mnuRegistro.setText("Registro");

        mniInscripcionMateria.setText("Inscripcion a materia");
        mnuRegistro.add(mniInscripcionMateria);

        barMainMenu.add(mnuRegistro);

        mnuSalir.setText("Salir");
        barMainMenu.add(mnuSalir);

        setJMenuBar(barMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAgregarAlumnoActionPerformed

    private void mniAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAgregarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMainMenu;
    private javax.swing.JMenuItem mniAgregarAlumno;
    private javax.swing.JMenuItem mniAgregarMateria;
    private javax.swing.JMenuItem mniInscripcionMateria;
    private javax.swing.JMenuItem mniListarAlumnos;
    private javax.swing.JMenuItem mniListarMaterias;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenu mnuMateria;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
