/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4.views;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tp4.entity.Alumno;

/**
 *
 * @author Mauricio
 */
public class MostrarAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarAlumnos
     */
    private final HashSet<Alumno> alumnos;

    public MostrarAlumnos(HashSet<Alumno> alumnos) {
        this.alumnos = alumnos;
        initComponents();       
        configurarTabla();      
        cargarTabla();          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcListaAlumnos = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Listado de Alumnos");

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        srcListaAlumnos.setViewportView(tblAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(srcListaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(srcListaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Legajo", "Apellido", "Nombre", "Materias"}, 0
        ) {
            @Override public boolean isCellEditable(int row, int col) { return false; }
        };
        tblAlumnos.setModel(model);          
        tblAlumnos.setAutoCreateRowSorter(true); 
    }

    private void cargarTabla() {
        DefaultTableModel model =
            (DefaultTableModel) tblAlumnos.getModel(); 

        java.util.List<Alumno> lista = new java.util.ArrayList<>(alumnos);
        lista.sort(java.util.Comparator
                .comparing(Alumno::getApellido, String.CASE_INSENSITIVE_ORDER)
                .thenComparing(Alumno::getNombre, String.CASE_INSENSITIVE_ORDER));

        model.setRowCount(0);
        for (Alumno a : lista) {
            model.addRow(new Object[]{
                a.getLegajo(),       
                a.getApellido(),
                a.getNombre(),
                a.cantidadMaterias()    
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane srcListaAlumnos;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Colegio aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
